#!/usr/bin/env bash
[[ $(id -u) -eq 0 ]] && {
    export PATH="$PATH:/usr/local/rvm/bin"
} || {
    source $HOME/.rvm/scripts/rvm
}
local RUBY_VERSION=$(rvm current)
rvm use $RUBY_VERSION >/dev/null
[[ $(id -u) -eq 0 ]] && {
    export PATH="$PATH:/usr/local/rvm/gems/$RUBY_VERSION/bin"
    export PATH="$PATH:/usr/local/rvm/rubies/$RUBY_VERSION/bin"
} || {
    export PATH="$PATH:$HOME/.rvm/gems/$RUBY_VERSION/bin"
    export PATH="$PATH:$HOME/.rvm/rubies/$RUBY_VERSION/bin"
}

