---

- name: Perpare hashicorp dependencies
  debug:
    msg: "Perpare hashicorp dependencies"
  changed_when: true
  notify:
    - Setup hashicorp

- name: Flush handlers
  meta: flush_handlers

- name: Update apt cache (hashicorp source only)  # noqa: command-instead-of-module
  become: true
  command: >
    apt-get update
    -o Dir::Etc::sourcelist="sources.list.d/hashicorp.list"
    -o Dir::Etc::sourceparts="-"
    -o APT::Get::List-Cleanup="0"
  changed_when: false

- name: Install terraform
  become: true
  apt:
    pkg:
      - terraform

- name: Enable terraform plugin cache
  template:
    src: .terraformrc.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.terraformrc"
    mode: 420
    backup: true
