---
- name: Gather version information for {{ tool_name }}
  include_tasks:
    file: check_tool_version.yml

- name: Install or update if needed for {{ tool_name }}
  shell: |
    volta install {{ package_name }}@latest
  args:
    executable: /bin/bash
  changed_when: lookup('vars', binary_name + '_needs_update') | default(false) | bool
  when: lookup('vars', binary_name + '_needs_update') | default(false) | bool
  register: managed_ai_tool_install_result

- name: Mark as up-to-date after install for {{ tool_name }}
  set_fact:
    "{{ binary_name }}_needs_update": false
  when:
    - managed_ai_tool_install_result is defined
    - not managed_ai_tool_install_result.skipped | default(false)
    - managed_ai_tool_install_result.rc == 0
