---
- name: Install and Configure Env Tools
  hosts: node
  vars_files:
    - vars/global.yml
    - roles/zsh/vars/gantsign.oh-my-zsh.yml
    - roles/ruby/vars/rvm.ruby.yml
  roles:
    - { role: init, tags: [init] }
    - { role: gantsign.oh-my-zsh, tags: [zsh] }
    - { role: zsh, tags: [zsh] }
    - { role: java, tags: [java] }
    - { role: node, tags: [node] }
    - { role: golang, tags: [golang] }
    - { role: rvm.ruby, tags: [ruby] }
    - { role: dotnet, tags: [dotnet] }
    - { role: docker, tags: [docker, minikube] }
    - { role: minikube, tags: [minikube] }
    - { role: kubeadm, tags: [kubeadm] }
    - { role: kubernetes_tools, tags: [kubernetes_tools, minikube] }
    - { role: cloud, tags: [cloud] }
    - { role: monitoring, tags: [monitoring] }
