[project]
name = "envmgr"
version = "0.1.0"
description = "Quick deployment to install and configure packages with ansible."
dependencies = [
    "ansible>=9.6.0",
    "kubernetes>=31.0.0",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ansible-lint>=24.5.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["scripts"]

[project.scripts]
install = "scripts:install"
create = "scripts:create"

[tool.rye.scripts]
ping = "ansible -m ping all"

setup = { chain = ["setup:sync-rye", "setup:init-logs", "setup:install-ansible-roles"] }
"setup:sync-rye" = "rye sync"
"setup:init-logs" = "mkdir -p log/"
"setup:install-ansible-roles" = "ansible-galaxy install -r requirements.yaml"

lint = "ansible-lint ./roles"
