---
prometheus_release_name: prometheus
prometheus_namespace: monitoring
prometheus_chart:
  repository: prometheus-community
  name: kube-prometheus-stack
  repo_url: https://prometheus-community.github.io/helm-charts

pod_wait_timeout: 600
pod_wait_retries: 30
pod_wait_delay: 10

# service config
prometheus_values:
  grafana:
    service:
      type: LoadBalancer
      port: 3000
    adminPassword: admin
    persistence:
      enabled: true
      size: 1Gi

  prometheus:
    service:
      type: LoadBalancer
      port: 9090

  alertmanager:
    service:
      type: LoadBalancer
      port: 9093
