name: ruby
description: RVM-based Ruby installation
enabled: true
targets:
  - workstation
tags:
  - ruby
depends_on: []
task_tags: []
vars_files:
  - roles/ruby/vars/rvm.ruby.yml
playbook_roles:
  - rvm.ruby
galaxy_roles:
  - rvm.ruby
collections: []
