---
# global vars file for zsh
omz:
  root: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh"
  plugins: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh/plugins"
  custom_plugins: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh/custom/plugins"
