#!/usr/bin/env bash
gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash

[[ $(id -u) -eq 0 ]] && export PATH="$PATH:/usr/local/rvm/bin" || source $HOME/.rvm/scripts/rvm
rvm pkg install openssl
rvm install 3.0.5 --with-openssl-dir=$HOME/.rvm/usr
rvm alias create default 3.0.5
load_env --ruby
gem install bundler rails