#!/usr/bin/env bash
sudo apt-get -y install bison
curl -sSL https://github.com/moovweb/gvm/raw/master/binscripts/gvm-installer | bash
source $HOME/.gvm/scripts/gvm
rm -rf $HOME/.gvm/archive
gvm install go1.20.1 -B
# go1.20.1
gvm use go1.20.1 --default
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn