#!/usr/bin/env zsh

# Set Device
Device='Remote'

## path
export PATH=$PATH:$HOME/.local/bin

## zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="lambda"
plugins=(
    git
    zsh-autosuggestions)

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

## alias
alias clr="clear"
alias gac="git add . && git commit"
alias gst="git status"

# reload
source ~/.oh-my-zsh/oh-my-zsh.sh
export PROMPT="%F{cyan}[$Device]%f $PROMPT"