#!/usr/bin/env zsh
## export
export ZSH="$HOME/.oh-my-zsh"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$PATH:$HOME/.local/bin

## theme and plugins
ZSH_THEME="lambda"
plugins=(
    git
    zsh-autosuggestions)
## alias
alias clr="clear"
alias gac="git add . && git commit"
alias gst="git status"

source ~/.oh-my-zsh/oh-my-zsh.sh
