---
- name: Add helm apt key
  become: true
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg
    state: present

- name: Get architecture
  command: dpkg --print-architecture
  changed_when: false
  register: arch_output

- name: Add helm apt repository
  become: true
  apt_repository:
    repo: "deb [arch={{ arch_output.stdout }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm

- name: Install helm
  become: true
  apt:
    update_cache: true
    pkg:
      - helm

- name: Install helm-diff plugin
  become: false
  shell: helm plugin install {{ helm.diff_plugin_url }}
  register: plugin_result
  changed_when: plugin_result.rc == 0
  failed_when:
    - plugin_result.rc != 0
    - '"plugin already exists" not in plugin_result.stderr'
