#!/usr/bin/env zsh

# Set Device
Device=`hostname -s`

# Loading
source ~/install/include/common.sh
load_path
load_zsh
load_nvm
load_alias
if_jammy_run disable_needrestart
set_git_config
reload_zsh $Device
