#!/usr/bin/env zsh

# Set Device
Device='wsl'

# Loading
source ~/install/include/common.sh
if_jammy_os disable_needrestart
set_git_config

# WSL2
wsl2_fix_interop
wsl2_startup_docker

# Load env
load_env --nvm --vagrant --alias --compose --zsh $Device