#!/usr/bin/env zsh

# Set Device
Device='wsl'

# Loading
source ~/install/include/common.sh
load_path
load_zsh
load_nvm
load_vagrant
load_alias
fix_wsl2_interop
if_jammy_run disable_needrestart
reload_zsh $Device
