#!/usr/bin/env bash
export PATH=$PATH:$HOME/install/lib/bin
alias clr="clear"
alias gac="git add . && git commit"
alias gst="git status"
alias gstb="git status -sb"
alias dps="docker ps -as"
alias dlog="docker logs --tail 50 --follow --timestamps"
alias dc="docker-compose"
alias vbm="vboxmanage"
alias cmq="mysql -h 127.0.0.1 -uroot -pmysql57"
alias crs="redis-cli -h 127.0.0.1 -p 6379 -a redis"
            