---
- name: Install and Configure node
  environment:
    VOLTA_HOME: "{{ ansible_facts['env']['HOME'] }}/.volta"
    PATH: "{{ volta_root }}/bin:{{ ansible_facts['env']['PATH'] }}"
    VOLTA_FEATURE_PNPM: "1"
  import_tasks: node.yml
