---
- name: Download volta installer if not exists
  get_url:
    url: https://get.volta.sh
    dest: "{{ installers_cache_dir }}/volta-installer"
    mode: "0755"
    force: false

- name: Install volta by volta installer
  script: "{{ installers_cache_dir }}/volta-installer"
  args:
    executable: /bin/bash
    creates: "{{ volta_root }}"

- name: Install node ( Default Version is {{ node_default_version }} )
  shell: |
    volta install node@{{ node_default_version }}
  args:
    executable: /bin/zsh
    creates: "{{ volta_root }}/bin/node"

- name: Install pnpm
  shell: |
    volta install pnpm@latest
  args:
    executable: /bin/zsh
    creates: "{{ volta_root }}/bin/pnpm"
