#!/usr/bin/env bash

# install python3 pip3
sudo apt-get -y install python3 python3-pip
pip3 install --upgrade pip

# install pyenv
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
load_env --python
