name: init
description: Base directories and host bootstrap tasks
enabled: true
targets:
  - workstation
  - node
tags:
  - init
depends_on: []
task_tags:
  - sync_time
  - git
  - github_cli
vars_files: []
playbook_roles:
  - init
galaxy_roles: []
collections: []
