name: init
description: Baseline workstation bootstrap bundle
enabled: true
targets:
  - workstation
tags:
  - init
depends_on:
  - init_core
task_tags:
  - github_cli
vars_files: []
playbook_roles:
  - init
galaxy_roles: []
collections: []
