---
# var file for role rvm.ruby
ruby_default_version: 3.0.5
rvm1_rubies:
  - "ruby-{{ ruby_default_version }}"
rvm1_bundler_install: true
rvm1_install_path: "{{ ansible_env.HOME }}/.rvm"
rvm1_install_flags: "--auto-dotfiles  --user-install"
rvm1_user: "{{ ansible_env.USER }}"
rvm1_rvm_latest_installer: "https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer"
rvm1_rvm_version: "stable"
rvm1_gpg_key_server: "hkp://pgp.mit.edu"
# 只使用可靠的 GPG 密钥服务器，避免连接失败
rvm1_gpg_key_servers:
  - "hkp://pgp.mit.edu"
