---
- name: Install and Configure Workstation Tools
  hosts: workstation
  vars_files:
    - ../vars/global.yml
    - ../roles/zsh/vars/gantsign.oh-my-zsh.yml
    - ../roles/ruby/vars/rvm.ruby.yml
  roles:
    - { role: init_core }
    - { role: init, tags: [init] }
    - { role: gantsign.oh-my-zsh, tags: [zsh] }
    - { role: zsh, tags: [zsh] }
    - { role: java, tags: [java] }
    - { role: node, tags: [node] }
    - { role: golang, tags: [golang] }
    - { role: rvm.ruby, tags: [ruby] }
    - { role: dotnet, tags: [dotnet] }
    - { role: docker, tags: [docker, minikube] }
    - { role: minikube, tags: [minikube] }
    - { role: kubernetes_tools, tags: [kubernetes_tools, minikube] }
    - { role: cloud, tags: [cloud] }
    - { role: ai_tools, tags: [ai_tools] }
