---
- name: Sync time
  import_tasks: sync_time.yml
  tags:
    - sync_time

- name: Update git
  import_tasks: git.yml
  tags:
    - git

- name: Setup GitHub CLI
  import_tasks: github_cli.yml
  tags:
    - github_cli
