name: init_core
description: Internal host-local prerequisites for dependent roles
enabled: true
targets:
  - workstation
  - node
tags: []
depends_on: []
task_tags: []
vars_files: []
playbook_roles:
  - init_core
galaxy_roles: []
collections: []
