#!/usr/bin/env zsh

# Set Device
local Device=$(hostname -s)

# Loading
export ENV_ROOT_DIR="env-manager"
source ${HOME}/${ENV_ROOT_DIR}/Manifest
source ${ENV_ROOT}/include/common.sh

if_jammy_os disable_needrestart

load_env \
    --node \
    --python \
    --golang \
    --alias \
    --docker \
    --git \
    --zsh $Device

# Custom
[[ -e ${ENV_LOAD}/zsh/settings/custom ]] && source ${ENV_LOAD}/zsh/settings/custom