#!/usr/bin/env zsh

# Set Device
local Device="Docker $(hostname -s)"

# Loading
source $HOME/install/include/common.sh

load_env \
    --nvm \
    --alias \
    --pyenv \
    --git \
    --ssh \
    --zsh $Device
