#!/usr/bin/env zsh

# Set Device
local Device="WSL: $(lsb_release -ds)"

export ENV_ROOT_DIR="env-manager"
source ${HOME}/${ENV_ROOT_DIR}/Manifest
source ${ENV_ROOT}/include/common.sh

if_jammy_os disable_needrestart

# WSL2
wsl2_config \
    --fix_interop \
    --startup_docker

load_env \
    --alias \
    --node \
    --python \
    --golang \
    --docker \
    --git \
    --vagrant \
    --zsh $Device

# Custom
[[ -e ${ENV_LOAD}/zsh/settings/custom ]] && source ${ENV_LOAD}/zsh/settings/custom