#!/usr/bin/env zsh

# Set Device
local Device='WSL'

export ENV_ROOT_DIR="env-manager"
source ${HOME}/${ENV_ROOT_DIR}/PROJECT_ENV
source ${ENV_ROOT}/include/common.sh

if_jammy_os disable_needrestart

# WSL2
wsl2_config \
    --fix_interop \
    --startup_docker

load_env \
    --node \
    --python \
    --golang \
    --alias \
    --docker \
    --git \
    --vagrant \
    --zsh $Device
