#!/usr/bin/env zsh

# Set Device
local Device='WSL'

# Loading
source $HOME/install/include/common.sh
if_jammy_os disable_needrestart

# WSL2
wsl2_config \
    --fix_interop \
    --startup_docker

# Load env
load_env \
    --nvm \
    --vagrant \
    --alias \
    --compose \
    --pyenv \
    --git \
    --zsh $Device
