#!/usr/bin/env bash

# Install Minikube
DEBFILE="minikube_latest_amd64.deb"

curl -LO https://storage.googleapis.com/minikube/releases/latest/$DEBFILE
sudo dpkg -i $DEBFILE
minikube version
minikube kubectl
rm -rf $DEBFILE
